In [ ]:
si = '*'
sj = '*'
for i in range(1,5,1):
    print(s*i)
for j in range(5,0, -1):
    print(s*j)

In [1]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as plt
from patsy import dmatrices
from sklearn.linear_model import LogisticRegression
from sklearn.cross_validation import train_test_split
from sklearn import metrics
from sklearn.cross_validation import cross_val_score

C:\Users\siddam\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [2]:
dta = sm.datasets.fair.load_pandas().data

In [3]:
dta.shape

(6366, 9)

In [4]:
dta.columns

Index(['rate_marriage', 'age', 'yrs_married', 'children', 'religious', 'educ',
       'occupation', 'occupation_husb', 'affairs'],
      dtype='object')

In [5]:
dta.occupation.unique()

array([2., 3., 5., 4., 1., 6.])

In [6]:
dta.occupation_husb.unique()

array([5., 4., 3., 2., 6., 1.])

In [7]:
dta.religious.unique()

array([3., 1., 2., 4.])

In [8]:
dta.educ.unique()

array([17., 14., 16., 12., 20.,  9.])

In [10]:
# add "affair" column: 1 represents having affairs, 0 represents not
dta['affair'] = (dta.affairs > 0).astype(int)
dta.head()

rate_marriage   age  yrs_married  children  religious  educ  occupation  \
0            3.0  32.0          9.0       3.0        3.0  17.0         2.0   
1            3.0  27.0         13.0       3.0        1.0  14.0         3.0   
2            4.0  22.0          2.5       0.0        1.0  16.0         3.0   
3            4.0  37.0         16.5       4.0        3.0  16.0         5.0   
4            5.0  27.0          9.0       1.0        1.0  14.0         3.0   

   occupation_husb   affairs  affair  
0              5.0  0.111111       1  
1              4.0  3.230769       1  
2              5.0  1.400000       1  
3              5.0  0.727273       1  
4              4.0  4.666666       1

In [ ]:
ya = dta.iloc[:,-1]
xa = dta.iloc[:,0:7]


In [11]:
y, X = dmatrices('affair ~ rate_marriage + age + yrs_married + children + \
                  religious + educ + C(occupation) + C(occupation_husb)',
                  dta, return_type="dataframe")
X.shape

(6366, 17)

In [ ]:
X.head()

In [12]:
y = np.ravel(y)

In [16]:
m = LogisticRegression()

In [14]:
model = m.fit(X,y)

In [17]:
model.score(X,y)

0.7258875274897895